add_executable(ubuntu_raw_blocking_st_server raw_blocking_single_server.cpp)
add_executable(ubuntu_raw_blocking_st_client raw_blocking_single_client.cpp)

add_executable(ubuntu_raw_blocking_mt_server raw_blocking_multi_server.cpp)
add_executable(ubuntu_raw_blocking_mt_client raw_blocking_multi_client.cpp)

target_link_libraries(ubuntu_raw_blocking_mt_server PRIVATE pthread)
target_link_libraries(ubuntu_raw_blocking_mt_client PRIVATE pthread)

add_executable(ubuntu_raw_blocking_pool_server raw_blocking_pool_server.cpp)
add_executable(ubuntu_raw_blocking_pool_client raw_blocking_pool_client.cpp)
target_link_libraries(ubuntu_raw_blocking_pool_server PRIVATE pthread)

add_executable(ubuntu_epoll_nonblocking_server epoll_nonblocking_server.cpp)
add_executable(ubuntu_epoll_nonblocking_client epoll_nonblocking_client.cpp)
